<?php declare(strict_types=1);?>
<body>
    <h3>サーバー情報は以下の通りです</h3>
    <table border="1">
        <tr>
            <th>PHP_SELF<br>(URLドキュメントルート以下)</th>
            <th><?=$_SERVER['PHP_SELF']?></th>
        </tr>
        <tr>
            <th>SERVER_ADDR<br>(WebサーバのIPアドレス)</th>
            <th><?=$_SERVER['SERVER_ADDR']?></th>
        </th>
        <tr>
            <th>SERVER_NAME<br>(Webサーバのホスト名)</th>
            <th><?=$_SERVER['SERVER_NAME']?></th>
        </th>
        <tr>
            <th>REQUEST_METHOD<br>(GETまたPOSTのメソッド名)</th>
            <th><?=$_SERVER['REQUEST_METHOD']?></th>
        </tr>
        <tr>
            <th>QUERY_STRING<br>(GETパラメータ文字列)</th>
            <th><?=$_SERVER['QUERY_STRING']?></th>
        </tr>
        <tr>
            <th>HTTP_REFERER<br>(クライアントから創出される遷移元のURL)</th>
            <th><?=$_SERVER['HTTP_REFERER']?></th>
        </tr>
        <tr>
            <th>HTTP_USER_AGENT<br>(クライアントのユーザー種別を表すUser-Agent文字列)</th>
            <th><?=$_SERVER['HTTP_USER_AGENT']?></th>
        </tr>
        <tr>
            <th>HTTPS<br>(httpは接続時には空欄、httpsは接続時は文字列)</th>
            <th><?=isset($_SERVER['HTTPS']) ? $_SERVER['HTTPS'] : '' ?>
        </tr>
        <tr>
            <th>REMOTE_ADDR<br>(クライアントのIPアドレス)</th>
            <th><?=$_SERVER['REMOTE_ADDR']?></th>
        </tr>
        <tr>
            <th>SCRIPT_FILENAME<br>(アクセスされているファイルの絶対パス)</th>
            <th><?=$_SERVER['SCRIPT_FILENAME']?></th>
        </tr>
        <tr>
            <th>SCRIPT_NAME<br>(アクセスされているPHPのURLのパス)</th>
            <th><?=$_SERVER['SCRIPT_NAME']?></th>
        </tr>
        <tr>
            <th>REQUEST_URI<br>(アクセスされているURI)</th>
            <th><?=$_SERVER['REQUEST_URI']?></th>
        </tr>
        <tr>
            <th>PATH_INFO<br>(URIのファイル名の後に付加されるパス名<br>これを使い、GETパラメータ付きURLを静的URLのように見せかけることができる)</th>
            <th><?=$_SERVER['PATH_INFO']?></th>
        </tr>
